api_v1/urls.py
from django.urls import path

from api_v1.views import json_add_view, json_divide_view, json_multiply_view, json_subtract_view

app_name = 'api_v1'

urlpatterns = [
    path('add/', json_add_view, name='add'),
    path('subtract/', json_subtract_view, name='subtract'),
    path('multiply/', json_multiply_view, name='multiply'),
    path('divide/', json_divide_view, name='divide'),
]

calculating/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from calculating.views import HomeView

app_name = 'calculating'

urlpatterns = [
    path('', HomeView.as_view(), name="home_page")
]

project/urls.py
from django.contrib import admin
from django.urls import path, include

api_list = [
    path('v1/', include('api_v1.urls')),
]

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('calculating.urls')),
    path('api/', include(api_list)),
]

calculating/models.py
from django.db import models

# Create your models here.

api_v1/views.py
import json
from django.http import JsonResponse


def json_add_view(request, *args, **kwargs):
    try:
        body = json.loads(request.body)
        add = int(body['A']) + int(body['B'])
        answer = {
            'answer': add
        }
        return JsonResponse(answer)
    except ValueError:
        response = JsonResponse({'error': 'Ошибка сложения! Одно из чисел является текстом'})
        response.status_code = 400
        return response


def json_subtract_view(request, *args, **kwargs):
    try:
        body = json.loads(request.body)
        subtract = int(body['A']) - int(body['B'])

        answer = {
            'answer': subtract
        }
        return JsonResponse(answer)
    except ValueError:
        response = JsonResponse({'error': 'Ошибка вычитания! Одно из чисел является текстом'})
        response.status_code = 400
        return response


def json_multiply_view(request, *args, **kwargs):
    try:
        body = json.loads(request.body)
        multiply = int(body['A']) * int(body['B'])
        answer = {
            'answer': multiply
        }
        return JsonResponse(answer)
    except ValueError:
        response = JsonResponse({'error': 'Ошибка умножения! Одно из чисел является текстом'})
        response.status_code = 400
        return response


def json_divide_view(request, *args, **kwargs):
    try:
        body = json.loads(request.body)
        divide = int(body['A']) / int(body['B'])
        answer = {
            'answer': divide
        }
        return JsonResponse(answer)
    except ValueError:
        response = JsonResponse({'error': 'Ошибка деления! Одно из чисел является текстом.'})
        response.status_code = 400
        return response
    except ZeroDivisionError:
        response = JsonResponse({'error': 'Ошибка деления! Одно из чисел является нулем. На ноль делить нельзя!'})
        response.status_code = 400
        return response

calculating/views.py
from django.views.generic import TemplateView


class HomeView(TemplateView):
    template_name = 'home.html'

templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">

    <script src="https://kit.fontawesome.com/d3482eb53a.js"></script>
    <title>{% block title %}{% endblock %}</title>
</head>
<body>

{% block content %}
{% endblock %}

<script src="{% static 'js/index.js' %}"></script>

</body>
</html>

templates/home.html
{% extends 'base.html' %}
{% block title %}Детальный просмотр{% endblock %}
{% block content %}
    <div class="mt-3">
        <div class="input-group mb-3">
            <span class="input-group-text" id="basic-addon1">Первое число</span>
            <input type="number" class="form-control" id="number_1" placeholder="Первое число" aria-label="number_1"
                   aria-describedby="basic-addon1">
        </div>
        <div class="input-group mb-3">
            <span class="input-group-text" id="basic-addon2">Второе число</span>
            <input type="text" class="form-control" id="number_2" placeholder="Второе число" aria-label="number_2"
                   aria-describedby="basic-addon1">
        </div>
        <div class="btn-group">
            <button type="submit" data-url="{% url 'api_v1:add' %}" data-method="POST"
                    class="btn calculating btn-primary">Сложение
            </button>
            <button type="submit" data-url="{% url 'api_v1:subtract' %}" data-method="POST"
                    class="btn calculating btn-info">Вычитание
            </button>
            <button type="submit" data-url="{% url 'api_v1:multiply' %}" data-method="POST"
                    class="btn calculating btn-success">Умножение
            </button>
            <button type="submit" data-url="{% url 'api_v1:divide' %}" data-method="POST"
                    class="btn calculating btn-dark">Деление
            </button>
            <span class="btn calculating btn-dark">Результат: <span id="result"></span></span>
        </div>
    </div>
{% endblock %}